

services:
  time-manager:
    build: .
    env_file:
      - .env
    container_name: time-manager
    ports:
      - "8080:80"
    volumes:
      - /home/cedri/websites/time-manager/src:/var/www/html
    user: root
  db:
    image: mysql:8.0
    container_name: time-manager-db
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      TZ: "America/Toronto"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data: